from .adicionarEstatisticas import adicionarEstatisticas
from .alunosPorTurmaListaEquipes import alunosPorTurmaListaEquipes
from .buscarAlunos import buscarAlunos
from .buscarAlunosPorTurma import buscarAlunosPorTurma
from .buscarClassificacoes import buscarClassificacoes
from .buscarEquipes import buscarEquipes
from .buscarEquipesPorEsporte import buscarEquipesPorEsporte
from .buscarEstatisticas import buscarEstatisticas
from .buscarEstatisticasPorId import buscarEstatisticasPorId
from .buscarEstatisticasDeModalidade import buscarEstatisticasDeModalidade
from .buscarEstatisticasPorModalidade import buscarEstatisticasPorModalidade
from .buscarEsportes import buscarEsportes
from .buscarEventosCalendario import buscarEventosCalendario
from .buscarJogadoresPorEquipe import buscarJogadoresPorEquipe
from .buscarModalidades import buscarModalidades
from .buscarPartidaPorId import buscarPartidaPorId
from .buscarPartidas import buscarPartidas
from .buscarTurmas import buscarTurmas
from .buscarUsuarioPorNome import buscarUsuarioPorNome
from .buscarUsuarios import buscarUsuarios
from .cadastrarAluno import cadastrarAluno
from .cadastrarAlunos import cadastrarAlunos
from .cadastrarEquipe import cadastrarEquipe
from .cadastrarEsportes import cadastrarEsportes
from .cadastrarEstatisticasParaModalidade import cadastrarEstatisticasParaModalidade
from .cadastrarTurma import cadastrarTurma
from .cadastrarUsuario import cadastrarUsuario
from .criarConexao import criarConexao
from .criarEstatisticas import criarEstatisticas
from .criarPartidas import criarPartidas
from .deletarAluno import deletarAluno
from .deletarEquipe import deletarEquipe
from .deletarTurma import deletarTurma
from .deletarUsuario import deletarUsuario
from .editarAluno import editarAluno
from .editarEquipe import editarEquipe
from .editarTurma import editarTurma
from .editarUsuario import editarUsuario
from .removerEstatisticas import removerEstatisticas
from .removerEstatisticasDaModalidade import removerEstatisticasDaModalidade
from .removerModalidade import removerModalidade
from .subirCargo import subirCargo
from .telaUsuarios import telaUsuarios
from .trocarSenha import trocarSenha